// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// MOUSE BITES MOUSE BITES MOUSE BITES MOUSE BITES
// // TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

// TOO MANY MOUSE BITES

import { useState } from "react";
import { StyleSheet, Text, View, TextInput } from "react-native";
import { AppButton } from "./AppButton";
import { colors } from "../assets/theme";

export function TodoInput({ onAddTodo }) {
  // TODO (state): replace this with a useState hook so the TextInput is
  const enteredTodo = "placeholder Text";

  // TODO (state): update enteredTodo with the text the user typed.
  const inputHandler = (text) => {};

  const addTodoHandler = () => {
    // TODO (logic): call onAddTodo(enteredTodo) to send the new todo up
    // to TodoSection
    // TODO (state): clear the input field afterwards (reset enteredTodo
    // back to "")
  };

  const cancelHandler = () => {
    // TODO (state): clear the input field without adding a todo
  };

  return (
    <View style={styles.inputSection}>
      <Text style={styles.inputSectionTitle}>Add a Doto</Text>
      {/* TODO: implement onChangeText, value, placeholder, placeholderTextColor, and style */}
      <TextInput />
      <Text style={styles.inputHint}>
        Type a task above, then tap Add Doto.
      </Text>
      <View style={styles.buttonContainer}>
        {/* TODO: wire onPress to addTodoHandler */}
        <AppButton text="Add Doto" />
        {/* TODO: wire onPress to cancelHandler */}
        <AppButton text="Cancel" />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  inputSection: {
    backgroundColor: colors.surface0,
    marginHorizontal: 20,
    padding: 16,
    borderRadius: 12,
  },
  inputSectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 10,
  },
  textInput: {
    backgroundColor: colors.mantle,
    color: colors.text,
    borderWidth: 2,
    borderColor: colors.surface1,
    borderRadius: 30,
    paddingHorizontal: 50,
    paddingVertical: 10,
    fontSize: 20,
  },
  inputHint: {
    fontSize: 12,
    color: colors.overlay,
    marginTop: 7,
    fontStyle: "italic",
  },
  buttonContainer: {
    flexDirection: "row",
    marginTop: 11,
    gap: 15,
  },
});
